name: Docker

on:
  push:
    branches: [main]
    tags: ["v*", "latest"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * 1"  # Every Monday at 02:00 UTC

jobs:
  docker:
    runs-on: ubuntu-latest # linux for custom runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: ${{ github.event_name == 'schedule' }}
          cache-from: ${{ github.event_name != 'schedule' && 'type=gha' || '' }}
          cache-to: ${{ github.event_name != 'schedule' && 'type=gha,mode=max' || '' }}
